baseURL = 'https://spikemurphy.github.io/BiochemProtocols/'
languageCode = 'en-us'
title = 'BiochemProtocols'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[security]
  enableInlineShortcodes = true

# Labjournal #
[outputFormats.JournalIndex]
  mediaType = "application/json"
  baseName = "journal"
  isPlainText = true
  notAlternative = true
[outputFormats.Body]
  mediaType = "text/html"
  baseName = "body"
  isPlainText = true
  notAlternative = true
# Labjournal #
