baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Laboratory'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[security]
  enableInlineShortcodes = true

[module]
  [[module.mounts]]
    source = "layouts/_shortcodes"
    target = "layouts/shortcodes"