baseURL = 'https://murphy-biochemistry.github.io/BiochemProtocolsWeb/'
languageCode = 'en-us'
title = 'BiochemProtocolsWeb'
author = "Spike Murphy Müller"
copyright = "© 2025 Murphy Biochemistry UG (haftungsbeschränkt) · All Rights Reserved"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[security]
  enableInlineShortcodes = true

# Labjournal #
[outputFormats.JournalIndex]
  mediaType = "application/json"
  baseName = "journal"
  isPlainText = true
  notAlternative = true
[outputFormats.Body]
  mediaType = "text/html"
  baseName = "body"
  isPlainText = true
  notAlternative = true
# Labjournal #
